### ISSUE TITLE
python bot.py

### ISSUE THREAD

**Issue by cowboysdude** [akshaybahadur21/Smart_Mirror#4]
Used wrong endpoint for microphone debugging
Traceback (most recent call last):
  File "bot.py", line 679, in <module>
    bot.start()
  File "bot.py", line 49, in start
    requests.get("http://localhost:8090/clear")
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /clear (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c58e6aa90>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by akshaybahadur21** [comment]
on which port is your smart mirror running. It is just that localhost port is wrong nothing else

**Comment by akshaybahadur21** [comment]
@cowboysdude - any updates on the issue?

**Comment by cowboysdude** [comment]
I have the mirror set to port 8090 but you have to start the bot.py first was my understanding....the mirror runs fine.  Just can't start the bot.py....all the ports in the bot.py are set to 8090....but there has to be an issue there because it continues to say it can't start on 8080....so where else is trying to load 8080 from?
Thank you

**Comment by cowboysdude** [comment]
Well apparently this just isn't going to work.  There should be no issue changing the port  to another port.  I've been running my server and mirror on different ports for months with no issue it's only the smart_mirror part that not working....

HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /microphone?enabled=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa61a0b9850>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "bot.py", line 679, in <module>
    bot.start()
  File "bot.py", line 49, in start
    requests.get("http://localhost:8090/clear")
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /clear (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa61a0b9890>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by ghost** [comment]
Is there a python3 version of this ?
