### ISSUE TITLE
Error: Could not find or load main class Py4JServer

### ISSUE THREAD

**Issue by ghadisaurabh** [akshaybahadur21/Smart_Mirror#6]
Error: Could not find or load main class Py4JServer
Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    from nlg import NLG
  File "C:\Users\sid_g\MagicMirror\AI-Smart-Mirror\nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "C:\Users\sid_g\MagicMirror\AI-Smart-Mirror\py4j_server\__init__.py", line 34, in launch_py4j_server
    _port = int(_pid.stdout.readline())
ValueError: invalid literal for int() with base 10: b''

**Comment by akshaybahadur21** [comment]
Have you followed the documentation for Mich Mich Magic Mirror installation? That is the base project.

**Comment by akshaybahadur21** [comment]
homebrew is not installed. @ghadisaurabh  are you running windows

**Comment by ghadisaurabh** [comment]
Yeah I am running windows....

**Comment by cowboysdude** [comment]
Won't work on windows but then it's not working on Linux either...

**Comment by akshaybahadur21** [comment]
@ghadisaurabh - It;s definetely not going to work on windows.... You must use ubuntu

**Comment by akshaybahadur21** [comment]
@cowboysdude - have you followed the mick mich guide... make sure that the base module by mich mich is running correctly.....Try using ubuntu

**Comment by ghadisaurabh** [comment]
Now I have installed ubuntu 16.04 but again I got same error:
siddheshghadi@siddheshghadi-Lenovo-B50-70:~/Smart_Mirror-master$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    from nlg import NLG
  File "/home/siddheshghadi/Smart_Mirror-master/nlg.py", line 4, in <module>
    from py4j_server import launch_py4j_server
  File "/home/siddheshghadi/Smart_Mirror-master/py4j_server/__init__.py", line 8, in <module>
    from py4j.java_gateway import JavaGateway, GatewayClient, java_import
ImportError: No module named py4j.java_gateway

**Comment by akshaybahadur21** [comment]
is brew and ruby installed on your device

**Comment by ghadisaurabh** [comment]
Okk.. so I have seen raghavpatnecha/smartmirror repository.It looks similar to yours. i have installed ruby and linuxbrew. ruby is installed in home directory and brew is installed in smart_mirror-master directory then setup.sh is also run(using sudo bash ./setup.sh). after this i have activated the virual evironment(using source hhsmartmirror/bin/activate from HackerHouseYT/AI-Smart-Mirror) and then run python bot.py
but it gave me error like this:
siddheshghadi@siddheshghadi-Lenovo-B50-70:~$ cd AI-Smart-Mirror
siddheshghadi@siddheshghadi-Lenovo-B50-70:~/AI-Smart-Mirror$ cd ..
siddheshghadi@siddheshghadi-Lenovo-B50-70:~$ cd Smart_Mirror-master
siddheshghadi@siddheshghadi-Lenovo-B50-70:~/Smart_Mirror-master$ source hhsmartmirror/bin/activate
(hhsmartmirror) siddheshghadi@siddheshghadi-Lenovo-B50-70:~/Smart_Mirror-master$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 13, in <module>
    from apiclient.discovery import build
ImportError: No module named apiclient.discovery
(hhsmartmirror) siddheshghadi@siddheshghadi-Lenovo-B50-70:~/Smart_Mirror-master$

as i have already installed apiclient ,it shows me this error..
so where should i installed ruby and brew like in which folder?
